### ISSUE TITLE
Use proxy pattern for function override where applicable

### ISSUE THREAD

**Issue by Type-kun** [Lightforger/Note-Assist#1]
Good to see the script here :3

Anyway, if you'll be doing code cleanup, take a look at http://api.jquery.com/Types/#Proxy_Pattern - it describes a technique to override an existing function without duplicating its code, in case you only need to append/prepend your code. For example, writing this:

``` javascript
var proxied = Danbooru.Note.TranslationMode.stop;
  Danbooru.Note.TranslationMode.stop = function() {
    $(".note-box-inner-border").unbind("click");
    return proxied.apply( this, arguments );
  };
```

 in `noteAssist_danbooruHooks()` allowed me to remove custom event binding I added in `TranslationMode.start`, and just call the default `TranslationMode.stop` functionality later using `proxied.apply( this, arguments );`. I'm pretty sure the majority of the hooks can be implemented this way, which will make them future-proof.

**Comment by Lightforger** [comment]
Interesting, the "arguments" variable is pretty useful. Much better solution than the one i had in mind (converting function to string & .replace(stuff))
Will add it to the script :)

I am working on the code cleanup, but I'm going to have to re-write the logic on some parts. Some things were horrible to maintain.

**Comment by Lightforger** [comment]
added this in v1.0
