### ISSUE TITLE
Feature request: save all changes

### ISSUE THREAD

**Issue by Type-kun** [Lightforger/Note-Assist#4]
Somewhat of a supplement to #3. The slowest part of note position maintenance is to hover every note, click on the body, and then click "save". If the script provided a button to automatically call "save" function on every _changed_ note, it would be super helpful. 

I think it's possible to determine if note was changed - since then have some sort of red border, it seems to imply notes can have "changed" state. 

Also, maybe this one should actually be integrated with the main site.

**Comment by Lightforger** [comment]
The only time the button would be useful would be when many notes are re-positioned without changing text, i doubt many people are doing that without this script.
It will be **"save all non-ghost notes"** to avoid confusion.

**Comment by Type-kun** [comment]
I don't know what causes that, exactly, but this function slows down considerably with each saved note - it's fast for a single note, but I have to wait for quite a log time to save 10+ notes. Also, all notes are left unfolded after that. Not exactly a big issue, but can be annoying nonetheless.

**Comment by Lightforger** [comment]
This opens the notes and presses the "save" button, the delay is most likely danbooru just taking a bit longer to process 10 requests at once. (could be getting throttled for anti-spam, dunno, how many seconds-ish?)

The note being unfolded after a safe is default functionality of danbooru, could be changed but is a bit tricker (would have to hijack the save response code)

**Comment by Type-kun** [comment]
> could be getting throttled for anti-spam, dunno, how many seconds-ish?

Can't say for sure but the delay gets progressively longer with each note, that's why I thought there's something wrong :3

Perhaps, just call the function directly instead of emulating the "save" click?

**Comment by Lightforger** [comment]
Looking at the danbooru code, it's already pretty much a direct call to the save API.
If during the delay your browser completely freezes (like, hovering over links no longer underlines them, can't change tabs, etc) then it's a javascript issue.
Tried it on 12 notes and couldn't reproduce it, took only 1-2 seconds for the "open all edit boxes and click save" and another 1 second for all notes to unfold. Tested  in opera 12.16.

```
save: function() {
  var $this = $(this);
  var $textarea = $this.find("textarea");
  var id = $this.data("id");
  var $note_body = Danbooru.Note.Body.find(id);
  var $note_box = Danbooru.Note.Box.find(id);
  var text = $textarea.val();
  $note_body.data("original-body", text);
  Danbooru.Note.Body.set_text($note_body, $note_box, "Loading...");
  $.get("/note_previews.json", {body: text}).success(function(data) {
    Danbooru.Note.Body.set_text($note_body, $note_box, data.body);
    Danbooru.Note.Box.resize_inner_border($note_box);
    $note_body.show();
  });
```
